import type {
  Agendamento,
  Cobranca,
  Conexao,
  Conta,
  Conversa,
  Regua,
  Transacao,
  UsoDiario,
} from "./types";

/** Data relativa a hoje, em ISO. Mantém o demo sempre "fresco". */
function d(offsetDias: number, horaStr = "09:00"): string {
  const [h, m] = horaStr.split(":").map(Number);
  const base = new Date();
  base.setHours(h, m, 0, 0);
  base.setDate(base.getDate() + offsetDias);
  return base.toISOString();
}

function hAtras(horas: number): string {
  return new Date(Date.now() - horas * 3600000).toISOString();
}

export const CONTA_DEMO: Conta = {
  id: "acc_demo",
  nomeEmpresa: "Clínica Vitalis",
  segmento: "Clínica / Consultório",
  nomeAtendente: "Sofia",
  tom: "amigavel",
  objetivos: ["atendimento", "cobranca", "agendamento"],
  email: "contato@clinicavitalis.com.br",
  whatsappPessoal: "5511987654321",
  horarioAtendimento: "Seg a Sex, 08h às 19h",
  planoId: "completo",
  periodo: "semestral",
  assinadoEm: d(-42),
  expiraEm: d(140),
  creditosUsados: 3184,
  creditosExtras: 0,
  conexoesExtras: 1,
  onboardingCompleto: true,
  notificarNovoAgendamento: true,
  notificarPagamento: true,
  notificarSemResposta: false,
};

/** Conta zerada, criada quando alguém percorre o cadastro do protótipo. */
export const CONTA_NOVA: Conta = {
  ...CONTA_DEMO,
  id: "acc_novo",
  nomeEmpresa: "",
  segmento: "",
  nomeAtendente: "",
  objetivos: [],
  email: "",
  whatsappPessoal: "",
  planoId: "profissional",
  periodo: "semestral",
  creditosUsados: 0,
  conexoesExtras: 0,
  onboardingCompleto: false,
};

export const REGUAS_DEMO: Regua[] = [
  {
    id: "reg_padrao",
    nome: "Régua padrão de mensalidade",
    descricao:
      "Lembra 3 dias antes, avisa no dia e cobra depois do vencimento até pagar.",
    ativa: true,
    aplicarA: "todas",
    tag: null,
    pausarAoResponder: false,
    pausarAoPagar: true,
    criadaEm: d(-40),
    stats: { enviadas: 412, respondidas: 168, recuperado: 18740 },
    etapas: [
      {
        id: "et_1",
        referencia: "vencimento",
        offsetDias: -3,
        hora: "09:00",
        condicao: "se_nao_pago",
        acao: "enviar_whatsapp",
        mensagem:
          "Oi {{nome}}! Aqui é a {{atendente}} da {{empresa}} 😊\nPassando só pra lembrar que sua {{descricao}} de {{valor}} vence em {{dias}} dias ({{vencimento}}).\nSe quiser, já te mando o PIX pra adiantar!",
        anexarPix: false,
        ativa: true,
      },
      {
        id: "et_2",
        referencia: "vencimento",
        offsetDias: 0,
        hora: "09:00",
        condicao: "se_nao_pago",
        acao: "enviar_whatsapp",
        mensagem:
          "Bom dia, {{nome}}! Hoje é o vencimento da sua {{descricao}} de {{valor}}.\nSegue o PIX pra facilitar 👇",
        anexarPix: true,
        ativa: true,
      },
      {
        id: "et_3",
        referencia: "vencimento",
        offsetDias: 2,
        hora: "10:00",
        condicao: "se_nao_pago",
        acao: "enviar_whatsapp",
        mensagem:
          "Oi {{nome}}, tudo bem? Vi aqui que a {{descricao}} de {{valor}} venceu {{prazo}} e ainda consta em aberto.\nAconteceu alguma coisa? Se precisar, consigo dividir pra você.",
        anexarPix: true,
        ativa: true,
      },
      {
        id: "et_4",
        referencia: "vencimento",
        offsetDias: 7,
        hora: "10:00",
        condicao: "se_nao_pago",
        acao: "oferecer_parcelamento",
        mensagem:
          "{{nome}}, consigo parcelar esses {{valor}} em até 3x no cartão ou dividir em 2 PIX.\nMe fala qual fica melhor que eu já organizo pra você 🙂",
        anexarPix: false,
        ativa: true,
      },
      {
        id: "et_5",
        referencia: "vencimento",
        offsetDias: 12,
        hora: "09:00",
        condicao: "se_nao_pago",
        acao: "notificar_voce",
        mensagem:
          "⚠️ {{nome}} está há 12 dias em atraso ({{valor}}) e não respondeu as últimas mensagens.",
        anexarPix: false,
        ativa: true,
      },
    ],
  },
  {
    id: "reg_pos",
    nome: "Agradecimento pós-pagamento",
    descricao: "Confirma o pagamento e pede indicação no dia seguinte.",
    ativa: true,
    aplicarA: "todas",
    tag: null,
    pausarAoResponder: false,
    pausarAoPagar: false,
    criadaEm: d(-25),
    stats: { enviadas: 186, respondidas: 74, recuperado: 0 },
    etapas: [
      {
        id: "et_p1",
        referencia: "pagamento",
        offsetDias: 0,
        hora: "12:00",
        condicao: "se_pago",
        acao: "enviar_whatsapp",
        mensagem:
          "Recebemos seu pagamento de {{valor}}, {{nome}}! Muito obrigada 💜\nQualquer coisa é só chamar aqui.",
        anexarPix: false,
        ativa: true,
      },
      {
        id: "et_p2",
        referencia: "pagamento",
        offsetDias: 1,
        hora: "15:00",
        condicao: "sempre",
        acao: "enviar_whatsapp",
        mensagem:
          "{{nome}}, se o atendimento da {{empresa}} te ajudou, você indicaria pra alguém? Isso ajuda demais a gente 🙏",
        anexarPix: false,
        ativa: false,
      },
    ],
  },
  {
    id: "reg_vip",
    nome: "Clientes VIP (toque manual)",
    descricao: "Cobrança mais suave e sempre com aviso pra você antes.",
    ativa: false,
    aplicarA: "tag",
    tag: "vip",
    pausarAoResponder: true,
    pausarAoPagar: true,
    criadaEm: d(-12),
    stats: { enviadas: 24, respondidas: 19, recuperado: 6200 },
    etapas: [
      {
        id: "et_v1",
        referencia: "vencimento",
        offsetDias: 1,
        hora: "11:00",
        condicao: "se_nao_pago",
        acao: "notificar_voce",
        mensagem: "Cliente VIP {{nome}} venceu ontem. Quer que eu cobre?",
        anexarPix: false,
        ativa: true,
      },
      {
        id: "et_v2",
        referencia: "vencimento",
        offsetDias: 3,
        hora: "11:00",
        condicao: "se_nao_pago",
        acao: "enviar_whatsapp",
        mensagem:
          "Oi {{nome}}, tudo certo? Só passando pra alinhar a {{descricao}} de {{valor}} que ficou pendente. Sem pressa 🙂",
        anexarPix: true,
        ativa: true,
      },
    ],
  },
];

export const COBRANCAS_DEMO: Cobranca[] = [
  {
    id: "cob_01",
    clienteNome: "Marina Alves",
    clienteTelefone: "5511991234501",
    descricao: "Sessão de limpeza de pele",
    valor: 280,
    vencimento: d(-14),
    status: "vencido",
    reguaId: "reg_padrao",
    tentativas: 4,
    ultimoEnvio: hAtras(26),
    pagoEm: null,
    tags: [],
  },
  {
    id: "cob_02",
    clienteNome: "Rodrigo Menezes",
    clienteTelefone: "5511991234502",
    descricao: "Plano mensal — Julho",
    valor: 420,
    vencimento: d(-6),
    status: "negociando",
    reguaId: "reg_padrao",
    tentativas: 3,
    ultimoEnvio: hAtras(8),
    pagoEm: null,
    tags: [],
  },
  {
    id: "cob_03",
    clienteNome: "Fernanda Lopes",
    clienteTelefone: "5511991234503",
    descricao: "Pacote 4 sessões",
    valor: 960,
    vencimento: d(-2),
    status: "vencido",
    reguaId: "reg_padrao",
    tentativas: 2,
    ultimoEnvio: hAtras(3),
    pagoEm: null,
    tags: ["vip"],
  },
  {
    id: "cob_04",
    clienteNome: "Carlos Eduardo Pinto",
    clienteTelefone: "5511991234504",
    descricao: "Avaliação + retorno",
    valor: 190,
    vencimento: d(0),
    status: "pendente",
    reguaId: "reg_padrao",
    tentativas: 1,
    ultimoEnvio: hAtras(5),
    pagoEm: null,
    tags: [],
  },
  {
    id: "cob_05",
    clienteNome: "Juliana Castro",
    clienteTelefone: "5511991234505",
    descricao: "Plano mensal — Agosto",
    valor: 420,
    vencimento: d(3),
    status: "pendente",
    reguaId: "reg_padrao",
    tentativas: 1,
    ultimoEnvio: hAtras(2),
    pagoEm: null,
    tags: [],
  },
  {
    id: "cob_06",
    clienteNome: "Patrícia Nogueira",
    clienteTelefone: "5511991234506",
    descricao: "Sessão avulsa",
    valor: 250,
    vencimento: d(6),
    status: "pendente",
    reguaId: "reg_padrao",
    tentativas: 0,
    ultimoEnvio: null,
    pagoEm: null,
    tags: ["vip"],
  },
  {
    id: "cob_07",
    clienteNome: "Bruno Tavares",
    clienteTelefone: "5511991234507",
    descricao: "Plano mensal — Julho",
    valor: 420,
    vencimento: d(-9),
    status: "pago",
    reguaId: "reg_padrao",
    tentativas: 2,
    ultimoEnvio: d(-8),
    pagoEm: d(-8),
    tags: [],
  },
  {
    id: "cob_08",
    clienteNome: "Aline Ribeiro",
    clienteTelefone: "5511991234508",
    descricao: "Pacote 2 sessões",
    valor: 520,
    vencimento: d(-4),
    status: "pago",
    reguaId: "reg_padrao",
    tentativas: 1,
    ultimoEnvio: d(-4),
    pagoEm: d(-3),
    tags: [],
  },
  {
    id: "cob_09",
    clienteNome: "Thiago Moraes",
    clienteTelefone: "5511991234509",
    descricao: "Consulta de retorno",
    valor: 160,
    vencimento: d(-1),
    status: "pago",
    reguaId: "reg_padrao",
    tentativas: 2,
    ultimoEnvio: d(-1),
    pagoEm: hAtras(20),
    tags: [],
  },
  {
    id: "cob_10",
    clienteNome: "Sandra Beatriz",
    clienteTelefone: "5511991234510",
    descricao: "Plano mensal — Agosto",
    valor: 420,
    vencimento: d(10),
    status: "pendente",
    reguaId: null,
    tentativas: 0,
    ultimoEnvio: null,
    pagoEm: null,
    tags: [],
  },
  {
    id: "cob_11",
    clienteNome: "Gustavo Henrique",
    clienteTelefone: "5511991234511",
    descricao: "Sessão de drenagem",
    valor: 300,
    vencimento: d(-22),
    status: "cancelado",
    reguaId: "reg_padrao",
    tentativas: 5,
    ultimoEnvio: d(-10),
    pagoEm: null,
    tags: [],
  },
];

export const CONVERSAS_DEMO: Conversa[] = [
  {
    id: "conv_01",
    contatoNome: "Marina Alves",
    contatoTelefone: "5511991234501",
    intencao: "cobranca",
    tags: ["inadimplente"],
    naoLidas: 2,
    ultimaAtividade: hAtras(0.3),
    modo: "ia",
    resumoIA:
      "Cliente com R$ 280 vencidos há 14 dias. Pediu para dividir em 2x. Aguardando sua aprovação de parcelamento.",
    mensagens: [
      {
        id: "m1",
        autor: "ia",
        texto:
          "Oi Marina, tudo bem? Aqui é a Sofia da Clínica Vitalis 😊\nSua sessão de limpeza de pele de R$ 280,00 venceu há 14 dias e ainda consta em aberto. Aconteceu alguma coisa?",
        hora: hAtras(3),
      },
      {
        id: "m2",
        autor: "cliente",
        texto: "Oi Sofia! Desculpa, esse mês apertou aqui 😩",
        hora: hAtras(2.5),
      },
      {
        id: "m3",
        autor: "cliente",
        texto: "Tem como dividir em duas vezes?",
        hora: hAtras(2.4),
      },
      {
        id: "m4",
        autor: "ia",
        texto:
          "Imagina, Marina, acontece! Consigo sim dividir em 2x de R$ 140,00 💜\nA primeira ficaria pra essa sexta e a segunda dia 15. Fecha assim?",
        hora: hAtras(2.2),
      },
      {
        id: "m5",
        autor: "cliente",
        texto: "Fecha! Pode mandar o pix da primeira",
        hora: hAtras(0.4),
      },
      {
        id: "m6",
        autor: "cliente",
        texto: "Obrigada pela paciência ❤️",
        hora: hAtras(0.3),
      },
    ],
  },
  {
    id: "conv_02",
    contatoNome: "Dra. Helena Prado",
    contatoTelefone: "5511991234520",
    intencao: "agendamento",
    tags: ["novo-cliente"],
    naoLidas: 0,
    ultimaAtividade: hAtras(1.2),
    modo: "ia",
    resumoIA:
      "Novo agendamento fechado pela IA: avaliação facial, quinta-feira às 14h. Já lançado na agenda.",
    mensagens: [
      {
        id: "m1",
        autor: "cliente",
        texto: "Boa tarde! Vocês têm horário essa semana pra avaliação?",
        hora: hAtras(2),
      },
      {
        id: "m2",
        autor: "ia",
        texto:
          "Boa tarde! Aqui é a Sofia da Clínica Vitalis 😊\nTemos sim! Essa semana consigo:\n• Quinta às 14h\n• Quinta às 16h30\n• Sexta às 10h\nQual fica melhor pra você?",
        hora: hAtras(1.9),
      },
      {
        id: "m3",
        autor: "cliente",
        texto: "Quinta às 14h é perfeito",
        hora: hAtras(1.4),
      },
      {
        id: "m4",
        autor: "ia",
        texto:
          "Fechado! Agendei sua avaliação facial pra quinta-feira às 14h ✅\nVou te mandar um lembrete 1 dia antes. Até lá!",
        hora: hAtras(1.3),
      },
      {
        id: "m5",
        autor: "sistema",
        texto:
          "Agendamento criado automaticamente e enviado pro WhatsApp pessoal do responsável.",
        hora: hAtras(1.2),
      },
    ],
  },
  {
    id: "conv_03",
    contatoNome: "Rodrigo Menezes",
    contatoTelefone: "5511991234502",
    intencao: "cobranca",
    tags: [],
    naoLidas: 1,
    ultimaAtividade: hAtras(8),
    modo: "humano",
    resumoIA:
      "Prometeu pagar os R$ 420 na segunda-feira. Você assumiu a conversa há 8 horas.",
    mensagens: [
      {
        id: "m1",
        autor: "ia",
        texto:
          "Oi Rodrigo! Sua mensalidade de julho (R$ 420,00) venceu há 6 dias. Consigo te ajudar com alguma forma de pagamento?",
        hora: hAtras(10),
      },
      {
        id: "m2",
        autor: "cliente",
        texto: "Recebo dia 5, dá pra segurar até segunda?",
        hora: hAtras(9),
      },
      {
        id: "m3",
        autor: "sistema",
        texto: "Você assumiu a conversa. A IA está pausada neste contato.",
        hora: hAtras(8.5),
      },
      {
        id: "m4",
        autor: "humano",
        texto:
          "Rodrigo, sem problema! Deixo anotado pra segunda então. Qualquer coisa me avisa 👍",
        hora: hAtras(8.2),
      },
      { id: "m5", autor: "cliente", texto: "Valeu demais 🙏", hora: hAtras(8) },
    ],
  },
  {
    id: "conv_04",
    contatoNome: "Camila Ferraz",
    contatoTelefone: "5511991234521",
    intencao: "duvida",
    tags: [],
    naoLidas: 0,
    ultimaAtividade: hAtras(20),
    modo: "ia",
    resumoIA:
      "Perguntou sobre valores do pacote de 4 sessões. IA respondeu e enviou tabela. Sem retorno até agora.",
    mensagens: [
      {
        id: "m1",
        autor: "cliente",
        texto: "Oi, quanto custa o pacote de 4 sessões?",
        hora: hAtras(21),
      },
      {
        id: "m2",
        autor: "ia",
        texto:
          "Oi! O pacote de 4 sessões sai por R$ 960,00, que dá R$ 240,00 a sessão (avulsa fica R$ 280,00).\nDá pra dividir em até 3x sem juros 😊\nQuer que eu já reserve um horário pra você?",
        hora: hAtras(20.9),
      },
      {
        id: "m3",
        autor: "cliente",
        texto: "Vou ver com meu marido e te falo",
        hora: hAtras(20),
      },
    ],
  },
  {
    id: "conv_05",
    contatoNome: "Fernanda Lopes",
    contatoTelefone: "5511991234503",
    intencao: "cobranca",
    tags: ["vip"],
    naoLidas: 0,
    ultimaAtividade: hAtras(3),
    modo: "ia",
    resumoIA:
      "Cliente VIP, R$ 960 vencidos há 2 dias. Disse que o PIX foi feito, aguardando comprovante.",
    mensagens: [
      {
        id: "m1",
        autor: "ia",
        texto:
          "Oi Fernanda! Passando pra avisar que o pacote de 4 sessões (R$ 960,00) venceu anteontem. Segue o PIX 👇",
        hora: hAtras(4),
      },
      {
        id: "m2",
        autor: "cliente",
        texto: "Já paguei ontem! Vou mandar o comprovante",
        hora: hAtras(3),
      },
    ],
  },
  {
    id: "conv_06",
    contatoNome: "Pedro Lima",
    contatoTelefone: "5511991234522",
    intencao: "agendamento",
    tags: [],
    naoLidas: 0,
    ultimaAtividade: hAtras(30),
    modo: "ia",
    resumoIA: "Remarcou a sessão de sexta para a próxima terça às 9h.",
    mensagens: [
      {
        id: "m1",
        autor: "cliente",
        texto: "Preciso remarcar minha sessão de sexta",
        hora: hAtras(31),
      },
      {
        id: "m2",
        autor: "ia",
        texto:
          "Sem problema, Pedro! Tenho terça às 9h ou quarta às 17h. Qual prefere?",
        hora: hAtras(30.8),
      },
      { id: "m3", autor: "cliente", texto: "Terça 9h", hora: hAtras(30.2) },
      {
        id: "m4",
        autor: "ia",
        texto: "Remarcado pra terça às 9h ✅ Te espero lá!",
        hora: hAtras(30),
      },
    ],
  },
];

export const AGENDAMENTOS_DEMO: Agendamento[] = [
  {
    id: "ag_01",
    clienteNome: "Dra. Helena Prado",
    clienteTelefone: "5511991234520",
    servico: "Avaliação facial",
    inicio: d(1, "14:00"),
    duracaoMin: 45,
    status: "confirmado",
    origem: "ia",
    observacao: "Primeira vez na clínica.",
  },
  {
    id: "ag_02",
    clienteNome: "Pedro Lima",
    clienteTelefone: "5511991234522",
    servico: "Sessão de drenagem",
    inicio: d(5, "09:00"),
    duracaoMin: 60,
    status: "confirmado",
    origem: "ia",
    observacao: "Remarcado pelo cliente.",
  },
  {
    id: "ag_03",
    clienteNome: "Juliana Castro",
    clienteTelefone: "5511991234505",
    servico: "Limpeza de pele",
    inicio: d(0, "16:30"),
    duracaoMin: 50,
    status: "confirmado",
    origem: "ia",
    observacao: "",
  },
  {
    id: "ag_04",
    clienteNome: "Carlos Eduardo Pinto",
    clienteTelefone: "5511991234504",
    servico: "Retorno",
    inicio: d(0, "11:00"),
    duracaoMin: 30,
    status: "concluido",
    origem: "manual",
    observacao: "",
  },
  {
    id: "ag_05",
    clienteNome: "Patrícia Nogueira",
    clienteTelefone: "5511991234506",
    servico: "Sessão avulsa",
    inicio: d(2, "10:00"),
    duracaoMin: 60,
    status: "pendente",
    origem: "ia",
    observacao: "Aguardando confirmação do cliente.",
  },
  {
    id: "ag_06",
    clienteNome: "Aline Ribeiro",
    clienteTelefone: "5511991234508",
    servico: "Pacote — sessão 2/2",
    inicio: d(3, "15:00"),
    duracaoMin: 60,
    status: "confirmado",
    origem: "ia",
    observacao: "",
  },
  {
    id: "ag_07",
    clienteNome: "Thiago Moraes",
    clienteTelefone: "5511991234509",
    servico: "Consulta de retorno",
    inicio: d(-1, "14:00"),
    duracaoMin: 30,
    status: "concluido",
    origem: "ia",
    observacao: "",
  },
  {
    id: "ag_08",
    clienteNome: "Sandra Beatriz",
    clienteTelefone: "5511991234510",
    servico: "Avaliação",
    inicio: d(4, "08:30"),
    duracaoMin: 45,
    status: "cancelado",
    origem: "ia",
    observacao: "Cliente cancelou pelo WhatsApp.",
  },
  {
    id: "ag_09",
    clienteNome: "Bruno Tavares",
    clienteTelefone: "5511991234507",
    servico: "Sessão de drenagem",
    inicio: d(6, "17:00"),
    duracaoMin: 60,
    status: "confirmado",
    origem: "ia",
    observacao: "",
  },
];

export const CONEXOES_DEMO: Conexao[] = [
  {
    id: "wpp_01",
    nome: "Recepção",
    numero: "5511933330001",
    status: "conectado",
    principal: true,
    mensagensMes: 2140,
    ultimaSync: hAtras(0.1),
  },
  {
    id: "wpp_02",
    nome: "Financeiro",
    numero: "5511933330002",
    status: "conectado",
    principal: false,
    mensagensMes: 1044,
    ultimaSync: hAtras(0.4),
  },
];

export const TRANSACOES_DEMO: Transacao[] = [
  {
    id: "tx_01",
    tipo: "assinatura",
    descricao: "Plano Completo — 6 meses",
    valor: 1770,
    data: d(-42),
    status: "pago",
    metodo: "pix",
  },
  {
    id: "tx_02",
    tipo: "conexao",
    descricao: "WhatsApp adicional (Financeiro)",
    valor: 49,
    data: d(-30),
    status: "pago",
    metodo: "pix",
  },
  {
    id: "tx_03",
    tipo: "creditos",
    descricao: "Pacote de 5.000 mensagens",
    valor: 169,
    data: d(-18),
    status: "pago",
    metodo: "pix",
  },
  {
    id: "tx_04",
    tipo: "conexao",
    descricao: "WhatsApp adicional (Financeiro)",
    valor: 49,
    data: d(0),
    status: "pago",
    metodo: "pix",
  },
];

export const USO_DEMO: UsoDiario[] = Array.from({ length: 14 }, (_, i) => {
  const dia = 13 - i;
  const base = [82, 61, 44, 97, 120, 88, 73, 51, 39, 110, 132, 95, 78, 64][i];
  return {
    data: d(-dia),
    atendimento: Math.round(base * 0.58),
    cobranca: Math.round(base * 0.27),
    agendamento: Math.round(base * 0.15),
  };
});

export const VARIAVEIS_MENSAGEM = [
  { chave: "{{nome}}", desc: "Primeiro nome do cliente", exemplo: "Marina" },
  { chave: "{{valor}}", desc: "Valor da cobrança", exemplo: "R$ 280,00" },
  { chave: "{{vencimento}}", desc: "Data de vencimento", exemplo: "05/08" },
  { chave: "{{dias}}", desc: "Dias até o vencimento", exemplo: "3" },
  { chave: "{{prazo}}", desc: "Prazo em texto", exemplo: "há 2 dias" },
  {
    chave: "{{descricao}}",
    desc: "Descrição da cobrança",
    exemplo: "sessão de limpeza de pele",
  },
  { chave: "{{empresa}}", desc: "Nome da sua empresa", exemplo: "Clínica Vitalis" },
  { chave: "{{atendente}}", desc: "Nome da sua atendente", exemplo: "Sofia" },
  { chave: "{{link_pix}}", desc: "PIX copia e cola", exemplo: "00020126..." },
];
